### ISSUE TITLE
todo/2016-10-10

### ISSUE THREAD

**Issue by BD-Joy** [BD-Joy/JiraClock#1]
- [ ] 导航条提成单独的component，以方便重用。
- [ ] 考虑下Issue item上应该放哪些按钮（Work log，Close，Clock Date，Priority等）
    - [ ] 后两者需要Backend支持，比如：如何存储数据？如何从Jira同步数据（定时抓取，还是查询时抓 取）？
    - [ ] 前两者项目是否太过简单，需要增加Add Task/Bug功能？

**Comment by BD-Joy** [comment]
“导航条的抽离“会产生问题：
无法弹出左侧导航菜单，而此菜单仅仅对Issues页面有用。

如何处理？

**Comment by BD-Joy** [comment]
考虑到Left Menu，导航条无法服用。
下期规划为：完成Create Task/Bug功能；目的：属性表单和表单验证。
